### ISSUE TITLE
cordova-plugin-sharesdk插件无法安装

### ISSUE THREAD

**Issue by cj1240** [zhaolin0801/cordova-plugin-sharesdk#1]
你好，使用您说得方法进行cordova plugin add cordova-plugin-sharesdk ，总是提示在搜索，后面我就是用cordova plugin search cordova-plugin-sharesdk命令，结果发现在官网上无法找到此插件呀，是怎么回事呀？要如何解决呢？

<img width="565" alt="111111" src="https://cloud.githubusercontent.com/assets/7079740/23933000/73438db2-0976-11e7-821c-dea11b879dff.png">

**Comment by anita-anita** [comment]
bogon:myShareSDKAPP anita$ cordova plugin list
cordova-plugin-console 1.0.6 "Console"
cordova-plugin-device 1.1.5 "Device"
cordova-plugin-sharesdk 0.1.0 "ShareSDK"
cordova-plugin-splashscreen 4.0.2 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
bogon:myShareSDKAPP anita$ cordova plugin remove cordova-plugin-sharesdk
Uninstalling cordova-plugin-sharesdk from ios
Error during processing of action! Attempting to revert...
Error: Uh oh!
Path must be a string. Received undefined
bogon:myShareSDKAPP anita$ 

这个怎么无法卸载？

**Comment by anita-anita** [comment]
bogon:myShareSDKAPP anita$ cordova plugin list
cordova-plugin-console 1.0.6 "Console"
cordova-plugin-device 1.1.5 "Device"
cordova-plugin-sharesdk 0.1.0 "ShareSDK"
cordova-plugin-splashscreen 4.0.2 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
bogon:myShareSDKAPP anita$ cordova plugin remove cordova-plugin-sharesdk
Uninstalling cordova-plugin-sharesdk from ios
Error during processing of action! Attempting to revert...
Error: Uh oh!
Path must be a string. Received undefined
bogon:myShareSDKAPP anita$

这个怎么无法卸载 执行的语句是：cordova plugin remove cordova-plugin-sharesdk

- [ ] 

- 1.

**Comment by cj1240** [comment]
@anita-anita   请问下你是怎么安装的啊？我怎么无法安装上去啊。提示没有这个插件！

**Comment by anita-anita** [comment]
进入到你创建的项目然后执行以下
cordova plugin add cordova-plugin-就可以安装了
sharesdk --variable SHARESDK_ANDROID_APP_KEY=xxxx --variable SHARESDK_IOS_APP_KEY=xxxx --variable WECHAT_APP_ID=xxxx --variable WECHAT_APP_SECRET=xxxx --variable WEIBO_APP_ID=xxxx --variable WEIBO_APP_SECRET=xxxx --variable WEIBO_REDIRECT_URL=http://xxxx --variable QQ_IOS_APP_ID=xxxx --variable QQ_IOS_APP_HEX_ID=xxxx --variable QQ_IOS_APP_KEY=xxxx --variable QQ_ANDROID_APP_ID=xxxx --variable QQ_ANDROID_APP_KEY=xxxx

**Comment by cj1240** [comment]
谢谢，我解决了，原因是因为我是在ionic里面，需要使用 ionic plugin add cordova-plugin命令

**Comment by anita-anita** [comment]
@cj1240  你是将插件下载下来之后再添加？  还是没有将插件下载下来，直接执行命令ionic plugin add cordova-plugin-sharesdk --variable SHARESDK_ANDROID_APP_KEY=xxxx --variable SHARESDK_IOS_APP_KEY=xxxx --variable WECHAT_APP_ID=xxxx --variable WECHAT_APP_SECRET=xxxx --variable WEIBO_APP_ID=xxxx --variable WEIBO_APP_SECRET=xxxx --variable WEIBO_REDIRECT_URL=http://xxxx --variable QQ_IOS_APP_ID=xxxx --variable QQ_IOS_APP_HEX_ID=xxxx --variable QQ_IOS_APP_KEY=xxxx --variable QQ_ANDROID_APP_ID=xxxx --variable QQ_ANDROID_APP_KEY=xxxx

第二种方法下载下来放在Documents的话是
直接执行命令ionic plugin add /User/anita/Documents/cordova-plugin-sharesdk-master  --variable SHARESDK_ANDROID_APP_KEY=xxxx --variable SHARESDK_IOS_APP_KEY=xxxx --variable WECHAT_APP_ID=xxxx --variable WECHAT_APP_SECRET=xxxx --variable WEIBO_APP_ID=xxxx --variable WEIBO_APP_SECRET=xxxx --variable WEIBO_REDIRECT_URL=http://xxxx --variable QQ_IOS_APP_ID=xxxx --variable QQ_IOS_APP_HEX_ID=xxxx --variable QQ_IOS_APP_KEY=xxxx --variable QQ_ANDROID_APP_ID=xxxx --variable QQ_ANDROID_APP_KEY=xxxx

我试了第二种方法不成功，插件添加了，但是点击分享按钮没反应
